version: "3.9"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: >
      sh -c "
      php artisan key:generate &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    volumes:
      - ./Backend:/var/www/backend
      - ./Backend/database:/var/www/backend/database
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/backend/database/database.sqlite

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=production
